name = "FastLevenshtein"
uuid = "f79185a3-a88d-4013-8848-f9f041a6cb9a"
authors = ["Matt Kearns mattkearns@protonmail.com"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Levenshtein = "cb002d51-b850-5775-a4f8-1db47be676b8"

[compat]
BenchmarkTools = "0.7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
